### ISSUE TITLE
Unable to provision Lucid32 box with Puppet using Vagrant 1.0.6

### ISSUE THREAD

**Issue by aelmadho** [pculture/amara-metrics#3]
I have created a box previously and I have been using it with vagrant 1.0.5 provisioned with a Puppet server.  I had no issues previously in provisioning the box, but since I have upgraded to Vagrant 1.0.6, this has stopped working.

I will attached the LOG shortly.

**Comment by aelmadho** [comment]
## Logs:

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /etc/debian_version (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /proc/version | grep 'Debian' (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /proc/version | grep 'Ubuntu' (sudo=false)
DEBUG ssh: Exit status: 0
 INFO vm: Loading guest: ubuntu
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: printf /vagrant (sudo=false)
DEBUG ssh: stdout: /vagrant
DEBUG ssh: Exit status: 0
DEBUG linux: Shell expanded guest path: /vagrant
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mkdir -p /vagrant (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` v-root /vagrant (sudo=true)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: chown `id -u vagrant`:`id -g vagrant` /vagrant (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: [ -x /sbin/initctl ] && /sbin/initctl emit vagrant-mounted MOUNTPOINT=/vagrant (sudo=true)
DEBUG ssh: Exit status: 0
 INFO interface: info: Running provisioner: Vagrant::Provisioners::PuppetServer...
[default] Running provisioner: Vagrant::Provisioners::PuppetServer...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: which puppet (sudo=true)
DEBUG ssh: Exit status: 0
 INFO interface: info: Running Puppet agent...
[default] Running Puppet agent...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ](sudo=true)
DEBUG ssh: stderr: stdin: is not a tty

 INFO interface: info: stdin: is not a tty
stdin: is not a tty
DEBUG ssh: stderr: Could not parse for environment xg1v3: Could not find file /home/vagrant/agent.pp
 INFO interface: info: Could not parse for environment xg1v3: Could not find file /home/vagrant/agent.pp
Could not parse for environment xg1v3: Could not find file /home/vagrant/agent.pp
DEBUG ssh: stderr: 

 INFO interface: info: 

DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VagrantError: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]>
ERROR vagrant: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/communication/ssh.rb:62:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/communication/ssh.rb:72:in`sudo'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/provisioners/puppet_server.rb:72:in `run_puppet_agent'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/provisioners/puppet_server.rb:25:in`provision!'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/provision.rb:34:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/provision.rb:31:in`each'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/provision.rb:31:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/forward_ports.rb:24:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/check_port_collisions.rb:42:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/env/set.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/clear_forwarded_ports.rb:13:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/clean_machine_folder.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/general/validate.rb:13:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/warden.rb:33:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/builder.rb:92:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/runner.rb:49:in`block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/action/runner.rb:49:in`run'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/vm.rb:192:in `run_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/vm.rb:152:in`start'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/up.rb:28:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/base.rb:116:in`block in with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/base.rb:111:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/base.rb:111:in`with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/command/up.rb:24:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/cli.rb:42:in`execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/environment.rb:167:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/bin/vagrant:43:in`<top (required)>'
/opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
/opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in`<main>'
 INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet agent --environment xg1v3 --certname cisco-vm --server cdbu-puppet --detailed-exitcodes || [ $? -eq 2 ]
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

**Comment by aelmadho** [comment]
Here is output of `id` command on vagrant user:

vagrant@ubuntu-lucid-32:~$ id
uid=1000(vagrant) gid=1000(vagrant) groups=4(adm),20(dialout),24(cdrom),46(plugdev),108(lpadmin),109(sambashare),110(admin),1000(vagrant)
